--[[
ScenEdit_RunScript ("lualumiere/SA_ReviewSM.lua")
ReviewSM()
]]
--not works in CMANO (no ability to modify SA script)!!

ScenEdit_RunScript ("lualumiere/Misc_UnixToDate.lua")

function ReviewSM()
  local event = ScenEdit_EventX ()

  for k, v in pairs (event.details.actions) do
    if v.Message then
      local ActionNameOrID = 'Review Special Message "' ..v.Message.Description.. '" (of Event ' ..event.details.description.. ') at ' ..UnixToDate(ScenEdit_CurrentTime() )
      local gsubtext = string.gsub(v.Message.Text, "&lt;", "<")
      local gsubtext2 = string.gsub(gsubtext, "&gt;", ">")
      local ScriptText =
        'local side = [[' ..v.Message.SideID.. ']] \r\n' ..
        'local text = [[' ..gsubtext2.. ']] \r\n' ..
        'ScenEdit_SpecialMessage(side, text)'

      ScenEdit_AddSpecialAction({side = v.Message.SideID, ActionNameOrID = ActionNameOrID, IsActive = true, IsRepeatable = true, ScriptText = ScriptText})
    else
      print("No Message for this event, or message may be generated by Lua script.")
    end
  end
end

--for Lua script SM
--[[
local side = sideABC
local text = etcetraetcetraetcetra
ScenEdit_SpecialMessage(side, text) --SM function for original script

local event = ScenEdit_EventX ()
local ActionNameOrID = 'Review Special Message in Lua Script "' ..v.LuaScript.Description.. '" (of Event ' ..event.details.description.. ') at ' ..UnixToDate(ScenEdit_CurrentTime() )
local ScriptText =
  'local side = [[' ..side.. ']] \r\n' ..
  'local text = [[' ..text.. ']] \r\n' ..
  'ScenEdit_SpecialMessage(side, text)'
ScenEdit_AddSpecialAction({side = v.Message.SideID, ActionNameOrID = ActionNameOrID, IsActive = true, IsRepeatable = true, ScriptText = ScriptText})
]]